export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';
export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const UPDATE_WIDTH = 'UPDATE_WIDTH';
export const UPDATE_HEIGHT = 'UPDATE_HEIGHT';
export const ADD_UNIVERSE_CELLS = 'ADD_UNIVERSE_CELLS';
export const UPDATE_ALL_STATUSES = 'UPDATE_ALL_STATUSES';
export const UPDATE_UNIVERSE_DIMENSIONS = 'UPDATE_UNIVERSE_DIMENSIONS';
