export const DEPLOY_UNIVERSE = 'DEPLOY_UNIVERSE';
export const CREATE_UNIVERSE_CELL_DATA = 'CREATE_UNIVERSE_CELL_DATA';
export const TOGGLE_ACTIVE = 'TOGGLE_ACTIVE';
export const TOGGLE_STATUS = 'TOGGLE_STATUS';
export const UPDATE_WIDTH = 'UPDATE_WIDTH';
export const UPDATE_HEIGHT = 'UPDATE_HEIGHT';
export const ADD_UNIVERSE_CELLS = 'ADD_UNIVERSE_CELLS';
export const UPDATE_ALL_STATUSES = 'UPDATE_ALL_STATUSES';
